name: "Test action"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
  workflow_dispatch:

jobs:
  test-upload-attachment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: sazid/zeuz-actions-deploy-preset@v1.0
        with:
          zeuz_preset_webhook: ${{ secrets.ZEUZ_PRESET_WEBHOOK }}
          zeuz_api_key: ${{ secrets.ZEUZ_API_KEY }}
          zeuz_node_id: ${{ vars.ZEUZ_NODE_ID }}
          zeuz_objective: ${{ vars.ZEUZ_OBJECTIVE }}
          zeuz_version: ${{ vars.ZEUZ_VERSION }}
